vpn/urls.py
from django.urls import path

from vpn import views

urlpatterns = [
    path("sites/", views.SiteListView.as_view(), name="site-list"),
    path("sites/create/", views.SiteCreateView.as_view(), name="site-create"),
    path("sites/<int:pk>/detail/", views.SiteDetailView.as_view(), name="site-detail"),
    path("sites/<int:pk>/update/", views.SiteUpdateView.as_view(), name="site-update"),
    path("sites/<int:pk>/delete/", views.SiteDeleteView.as_view(), name="site-delete"),
    path("<path:url>", views.ProxyView.as_view(), name="site-proxy"),
]


app_name = "vpn"

vpn_service/urls.py
from django.contrib import admin
from django.urls import path, include

from vpn.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("users/", include("users.urls")),
    path("vpn/", include("vpn.urls")),
]

vpn/models.py
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


class Site(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.PROTECT, related_name="sites"
    )

    class Meta:
        unique_together = [("url", "author")]


class Statistics(models.Model):
    site = models.OneToOneField(
        Site, on_delete=models.CASCADE, related_name="statistics"
    )
    transitions_number = models.PositiveIntegerField(default=0)
    data_volume_upload = models.PositiveBigIntegerField(
        help_text="Обʼєм даних який було відправлено (в байтах)",
        default=0,
    )
    data_volume_downloaded = models.PositiveBigIntegerField(
        help_text="Обʼєм даних який було завантажено (в байтах)",
        default=0,
    )

vpn/forms.py
from django import forms
from django.core.exceptions import ValidationError

from vpn.models import Site, Statistics


class SiteSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by site name..."}),
    )


class SiteCreateForm(forms.ModelForm):
    class Meta:
        model = Site
        fields = ["name", "url"]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def clean(self):
        url_data = self.cleaned_data["url"]
        unified_url = url_data.strip("/").replace("https", "http")
        if Site.objects.filter(url=unified_url, author=self.request.user).exists():
            raise ValidationError("You already added this site")

        self.cleaned_data["url"] = unified_url
        return self.cleaned_data

    def save(self, commit=True):
        self.instance = super().save(commit=False)
        self.instance.author = self.request.user
        self.instance.save()

        Statistics.objects.create(site=self.instance)

        return self.instance


class SiteNameUpdateForm(forms.ModelForm):
    class Meta:
        model = Site
        fields = ["name"]

vpn/views.py
from urllib.parse import unquote, urlparse

import requests
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from vpn.forms import SiteSearchForm, SiteNameUpdateForm, SiteCreateForm
from vpn.models import Site
from vpn.services.parser import HTMLParser


@login_required
def index(request):
    """View function for the home page of the site."""

    context = {
        "num_all_tasks": 0,
        "num_tasks_done": 0,
        "num_workers": 0,
        "today_tasks": 0,
        "percentage": 0,
    }

    return render(request, "vpn/index.html", context=context)


class UserSitesMixin:
    def get_queryset(self):
        return Site.objects.filter(author=self.request.user)


class SiteListView(LoginRequiredMixin, UserSitesMixin, generic.ListView):
    model = Site
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = SiteSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = super().get_queryset()

        form = SiteSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class SiteDetailView(LoginRequiredMixin, UserSitesMixin, generic.DetailView):
    model = Site


class SiteCreateView(LoginRequiredMixin, generic.CreateView):
    model = Site
    success_url = reverse_lazy("vpn:site-list")
    form_class = SiteCreateForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs


class SiteUpdateView(LoginRequiredMixin, UserSitesMixin, generic.UpdateView):
    model = Site
    form_class = SiteNameUpdateForm

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("vpn:site-detail", kwargs={"pk": pk})


class SiteDeleteView(LoginRequiredMixin, UserSitesMixin, generic.DeleteView):
    model = Site
    success_url = reverse_lazy("vpn:site-list")


class ProxyView(LoginRequiredMixin, generic.View):
    def get(self, request, url, *args, **kwargs):
        decoded_url = unquote(url)
        response = requests.get(decoded_url)

        if response.status_code == 200:
            domain = urlparse(decoded_url).netloc
            uploaded_bytes = len(response.request.body) if response.request.body else 0
            downloaded_bytes = response.headers.get("content-length") or len(
                response.content
            )

            website = Site.objects.get(url__icontains=domain, author=self.request.user)
            website.statistics.transitions_number += 1
            website.statistics.data_volume_downloaded += downloaded_bytes
            website.statistics.data_volume_upload += uploaded_bytes
            website.statistics.save(
                update_fields=[
                    "transitions_number",
                    "data_volume_downloaded",
                    "data_volume_upload",
                ]
            )

            refactored_response_text = HTMLParser(response).change_routing()

            return HttpResponse(
                refactored_response_text, content_type=response.headers["content-type"]
            )

        return render(request, "vpn/proxy_error.html")

templates/vpn/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <div class="container-fluid py-4">

      <div class="row">
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
          <div class="card">
            <div class="card-body p-3">
              <div class="row">
                <div class="col-8">
                  <div class="numbers">
                    <h5 class="font-weight-bolder mb-0">
                      <a class="nav-link {% if 'users:detail' in segment %} active {% endif %} " href="{% url 'users:detail' pk=user.id%}"
                        <span class="nav-link-text ms-1">My profile</span>
                      </a>
                    </h5>
                  </div>
                </div>
                <div class="col-4 text-end">
                  <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                    <i class="ni ni-satisfied text-lg opacity-10" aria-hidden="true"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
          <div class="card">
            <div class="card-body p-3">
              <div class="row">
                <div class="col-8">
                  <div class="numbers">
                    <h5 class="font-weight-bolder mb-0">
                      <a class="nav-link {% if 'vpn:site-list' in segment %} active {% endif %} " href="{% url 'vpn:site-list' %}"
                        <span class="nav-link-text ms-1">Sites</span>
                      </a>
                    </h5>
                  </div>
                </div>
                <div class="col-4 text-end">
                  <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                    <i class="ni ni-world-2 text-lg opacity-10" aria-hidden="true"></i>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
{% endblock %}

templates/vpn/proxy_error.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-12">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <h6>Error occurred when trying to get destination site</h6>
          </div>
          <div class="card-body px-0 pt-0 pb-2">
            <a class="btn bg-gradient-secondary" href="{% url 'vpn:site-list' %}">Sites list</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/vpn/site_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-12">
        <div class="card mb-4">
          <div class="card-header pb-0">
            <h6>Are you sure you want to delete {{ site.name }} site?</h6>
          </div>
          <div class="card-body px-0 pt-0 pb-2">
            <form action="" method="post">
              {% csrf_token %}

              <input type="submit" value="Yes" class="btn bg-gradient-danger">
              <a class="btn bg-gradient-secondary" href="{% url 'vpn:site-list' %}">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/vpn/site_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-12">
          <div class="card h-100">
            <div class="card-header pb-0 p-3">
              <div class="row">
                <div class="col-md-8 d-flex align-items-center">
                  <h5 class="font-weight-bolder">{{ site.name }}</h5>
                </div>
                <div class="col-md-4 text-end">
                  <a class="btn bg-gradient-dark mb-0" href="{% url 'vpn:site-update' pk=site.id %}">Edit</a>
                  <a class="btn bg-gradient-danger mb-0" href="{% url 'vpn:site-delete' pk=site.id %}">Delete</a>
                </div>
              </div>
            </div>
            <div class="card-body p-3">
              <hr class="horizontal gray-light my-2">
              <ul class="list-group">
                <li class="list-group-item border-0 ps-0 text-sm"><strong class="text-dark">Url:</strong>
                  <a href="{{ site.url }}">{{ site.url }}</a>
                </li>
                <li class="list-group-item border-0 ps-0 text-sm">
                   <a class="btn bg-gradient-dark mb-0" href="{% url 'vpn:site-proxy' url=site.url %}">Go to Website</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <br>
  </div>

{% endblock %}

templates/vpn/site_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container-fluid py-4">
    <h5 class="font-weight-bolder">{{ object|yesno:"Update,Create" }} site</h5>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}

templates/vpn/site_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}

{% block content %}

    <div class="container-fluid py-4">
      <div class="row">
        <form action="" method="get" class="d-flex flex-row align-items-center flex-wrap">
          {{ search_form|crispy }}
          <input type="submit" value="🔍" class="btn bg-gradient-white">
        </form>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            {% if site_list %}
              <div class="card-header pb-0">
                <div class="row">
                  <div class="col-6 d-flex align-items-center">
                    <h6 class="mb-0">List of all sites</h6>
                  </div>
                  <div class="col-6 text-end">
                    <a class="btn bg-gradient-dark mb-0" href="{% url 'vpn:site-create' %}"><i class="fas fa-plus"></i>&nbsp;&nbsp;New Site</a>
                  </div>
                </div>
              </div>
              <div class="card-body px-0 pt-0 pb-2">
                <div class="table-responsive p-0">
                  <table class="table align-items-center justify-content-center mb-0">
                    <thead>
                      <tr>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Name</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Url</th>
                        <th class="text-secondary opacity-7"></th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for site in site_list %}
                        <tr>
                          <td>
                            <div class="d-flex px-2">
                              <div class="my-auto">
                                <h6 class="mb-0 text-sm"><a href="{% url 'vpn:site-detail' pk=site.id%}">{{ site.name }}</a></h6>
                              </div>
                            </div>
                          </td>
                          <td>
                            <p class="text-sm font-weight-bold mb-0"><a href="{{ site.url }}">{{ site.url }}</a></p>
                          </td>
                          <td>
                            <a class="btn btn-link text-dark text-gradient px-3 mb-0" href="{% url 'vpn:site-proxy' url=site.url %}">Go to Website</a>
                          </td>
                          <td>
                            <a class="btn btn-link text-danger text-gradient px-3 mb-0" href="{% url 'vpn:site-delete' pk=site.id %}"><i class="far fa-trash-alt me-2"></i>Delete</a>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            {% else %}
              <div class="card-header pb-0">
                <div class="row">
                  <div class="col-6 d-flex align-items-center">
                    <h6 class="mb-0">No sites yet</h6>
                  </div>
                  <div class="col-6 text-end">
                    <a class="btn bg-gradient-dark mb-0" href="{% url 'vpn:site-create' %}"><i class="fas fa-plus"></i>&nbsp;&nbsp;New Site</a>
                  </div>
                </div>
                <div class="card-body px-0 pt-0 pb-2"></div>
              </div>
            {% endif %}
          </div>
        </div>
      </div>

    </div>
{% endblock %}