users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("register/", views.UserCreateView.as_view(), name="register"),
    path("", include("django.contrib.auth.urls")),
    path("<int:pk>/detail/", views.UserDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.UserUpdateView.as_view(), name="update"),
]

app_name = "users"

vpn/urls.py
from django.urls import path

from vpn import views

urlpatterns = [
    path("sites/", views.SiteListView.as_view(), name="site-list"),
    path("sites/create/", views.SiteCreateView.as_view(), name="site-create"),
    path("sites/<int:pk>/detail/", views.SiteDetailView.as_view(), name="site-detail"),
    path("sites/<int:pk>/update/", views.SiteUpdateView.as_view(), name="site-update"),
    path("sites/<int:pk>/delete/", views.SiteDeleteView.as_view(), name="site-delete"),
    path("<path:url>", views.ProxyView.as_view(), name="site-proxy"),
]


app_name = "vpn"

vpn_service/urls.py
from django.contrib import admin
from django.urls import path, include

from vpn.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="index"),
    path("users/", include("users.urls")),
    path("vpn/", include("vpn.urls")),
]

users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError(_("The Email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = models.CharField(_("username"), max_length=150, blank=True, null=True)
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.username = self.email.split("@")[0]
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ["email", "first_name", "last_name", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["username", "first_name", "last_name"]

users/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views import generic

from users.forms import RegisterForm, UserUpdateForm
from vpn.models import Statistics


class UserCreateView(generic.CreateView):
    form_class = RegisterForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        response = super().form_valid(form)

        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, email=email, password=password)

        if user is not None:
            login(self.request, user)

        return response


class UserDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()
    queryset = get_user_model().objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_statistics = Statistics.objects.select_related("site__author").filter(
            site__author=self.request.user
        )
        context["sites_stats"] = user_statistics
        return context


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("users:detail", kwargs={"pk": pk})

templates/users/user_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid py-4">
    <div class="row">
      <div class="col-12">
          <div class="card h-100">
            <div class="card-header pb-0 p-3">
              <div class="row">
                <div class="col-md-8 d-flex align-items-center">
                  <h5 class="font-weight-bolder">Username: {{ user.username }}</h5>
                </div>
                <div class="col-md-4 text-end">
                  <a class="btn bg-gradient-dark mb-0" href="{% url 'users:update' pk=user.id %}">Edit</a>
                </div>
              </div>
            </div>
            <div class="card-body p-3">
              <p class="text-sm">
                {{ user.first_name }} {{ user.last_name }}
              </p>
              <p class="text-sm">
                {{ user.email }}
              </p>
            </div>
          </div>
        </div>
      </div>
    <br>
    {% if sites_stats %}
      <div class="row">
        <div class="col-12">
          <div class="card mb-4">
            <div class="card-header pb-0">
              <h6>Статистика по сайтах</h6>
            </div>
            <div class="card-body px-0 pt-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                  <tr>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Назва</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Url</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Кількість переходів</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Обʼєм даних який було відправлено (в байтах)</th>
                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Обʼєм даних який було завантажено (в байтах)</th>
                    <th class="text-secondary opacity-7"></th>
                  </tr>
                  </thead>
                  <tbody>
                      {% for statistic in sites_stats %}
                        <tr>
                          <td>
                            <div class="d-flex px-2 py-1">
                              <div class="d-flex flex-column justify-content-center">
                                <h6 class="mb-0 text-sm">{{ statistic.site.name }}</h6>
                              </div>
                            </div>
                          </td>
                          <td>
                            <p class="text-xs font-weight-bold mb-0">{{ statistic.site.url }}</p>
                          </td>
                          <td>
                            <p class="text-xs font-weight-bold mb-0">{{ statistic.transitions_number }}</p>
                          </td>
                          <td>
                            <p class="text-sm font-weight-bold mb-0">{{ statistic.data_volume_upload }}</p>
                          </td>
                          <td>
                            <p class="text-sm font-weight-bold mb-0">{{ statistic.data_volume_downloaded }}</p>
                          </td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
    {% else %}
      <div class="card-header pb-0">
        <h6>У вас ще не додано жодного сайту</h6>
      </div>
    {% endif %}
  </div>

{% endblock %}

templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container-fluid py-4">
    <h5 class="font-weight-bolder">Update User</h5>
    <form action="" method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}

      <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </div>
{% endblock %}